export declare const MAX_MESSAGE_LENGTH = 428;
export declare const MAX_NAMESPACE_LENGTH = 30;
export declare const MAX_EVENT_ID_LENGTH = 70;
export declare const HANDLER_MESSAGE_PADDING: number;
export declare const STREAM_MESSAGE_PADDING: number;
export type ScriptEventListener<TPayload> = (payload: TPayload) => void;
export type ScriptEventHandler<TPayload, TResponse> = (payload: TPayload) => TResponse;
export declare function registerScriptEventListener<TPayload>(event: string, callback: ScriptEventListener<TPayload>): void;
export declare function removeScriptEventListener(event: string): boolean;
export declare function registerScriptEventStreamListener<TPayload>(event: string, callback: ScriptEventListener<TPayload>): void;
export declare function removeScriptEventStreamListener(event: string): boolean;
export declare function registerScriptEventHandler<TPayload, TResponse>(event: string, callback: ScriptEventHandler<TPayload, TResponse>): void;
export declare function removeScriptEventHandler(event: string): boolean;
export declare function dispatchScriptEventRaw(event: string, message: string): void;
export declare function dispatchScriptEvent(event: string, payload: unknown, force?: boolean): void;
export declare function invokeScriptEvent(event: string, namespace: string, payload: unknown, force?: boolean): Promise<unknown>;
export declare function streamScriptEvent(event: string, namespace: string, payload: unknown, force?: boolean): Generator<void, void, void>;
