// The implementation of this declaration file is
// auto-generated by scripts/filters/tiled_icons.ts

/**
 * The short IDs (`ui_${icon}_${tileX}_${tileY}`) of the icon tiles that are
 * fully transparent. Those tiles render as nothing, so the `tiled_icons` build filter
 * generates no item or texture for them.
 */
declare const TRANSPARENT_ICON_TILES: ReadonlySet<string>;
/**
 * The short ID of each icon tile that shares its texture with an earlier tile,
 * mapped to the short ID of that tile. The `tiled_icons` build filter generates no
 * item or texture of its own for these.
 */
declare const ICON_TILE_REDIRECTS: Readonly<Record<string, string>>;
export { TRANSPARENT_ICON_TILES, ICON_TILE_REDIRECTS };
