// The implementation of this declaration file is
// auto-generated by scripts/filters/tutorial_book_entries.ts

declare interface TutorialEntry {
  bullets: number;
}
declare const TUTORIAL_ENTRIES: Record<string, TutorialEntry>;
export { TUTORIAL_ENTRIES, TutorialEntry };
