// The implementation of this declaration file is
// auto-generated by scripts/filters/tutorial_book_entries.ts

declare interface TutorialEntry {
  id: string;
  bullets: number;
}
declare const TUTORIAL_ENTRIES: TutorialEntry[];
export { TUTORIAL_ENTRIES, TutorialEntry };
